services:
  db:
    image: mariadb:11
    restart: unless-stopped
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  app:
    image: nextcloud:apache
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=username
      - MYSQL_HOST=db
      - REDIS_HOST=redis

  cron:
    image: nextcloud:apache
    container_name: cron
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    environment:
      - domain=nextcloud\\.localhost #Change this line, according to the domain your nextcloud is on
      - username=admin
      - password=password
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    ports:
      - 9980:9980
