{
 "title": "Synology Dashboard",
 "description": "Grafana Dashboard for Synology Devices, collecting SNMP using Telegraf, and InfluxDB",
 "tags": [ "synology" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "synologyhostname",
    "label": "Hostname",
    "query": {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] != \"\")\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()\r\n  \r\n"
    }
   },
   { "name": "Bucket", "query": { "query": "buckets()" } }
  ]
 },
 "panels": [
  { "title": "Synology Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synology Overview - $synologyhostname",
   "type": "stat",
   "description": "This panel displays all the needed Synology information of the unit you are running.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "synologyhostname",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"synoSystem.modelName\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct(column: \"_value\")\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) "
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"synoSystem.version\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct(column: \"_value\")\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) "
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory.memTotalReal\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) \r\n"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemStats.ssCpuNumCpus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) "
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.disk\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> keep(columns: [\"diskID\"])\r\n  |> distinct(column: \"diskID\")\r\n  |> group()\r\n  |> count()"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.network\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> keep(columns: [\"ifDescrEX\"])\r\n  |> distinct(column: \"ifDescrEX\")\r\n  |> group()\r\n  |> count()"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrSystem.hrSystemUptime\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> map(fn: (r) => ({r with _value: r._value / 360000}))\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) \r\n\r\n"
    }
   ]
  },
  { "title": "Synology Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "FAN Status - $synologyhostname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "repeat": "synologyhostname",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"synoSystem.cpuFanStatus\")\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"synoSystem.systemFanStatus\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "System Temperatures - $synologyhostname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 7 },
   "repeat": "synologyhostname",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"synoSystem.temperature\")\r\n  |> aggregateWindow(every: ${interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk Temperatures - $synologyhostname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 7 },
   "repeat": "synologyhostname",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.disk\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskTemperature\")\r\n  |> aggregateWindow(every: ${interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Synology Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Services",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"serviceUsers\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disks Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskModel\" or r[\"_field\"] == \"diskStatus\" or r[\"_field\"] == \"diskType\" or r[\"_field\"] == \"diskTemperature\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> last()\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group()"
    }
   ]
  },
  { "title": "Synology System Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "numCpus = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemStats.ssCpuNumCpus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\", \"systemStats.ssCpuNumCpus\"])\r\n\r\nstats = from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"systemStats.ssCpuRawSystem\" or r[\"_field\"] == \"systemStats.ssCpuRawUser\" or r[\"_field\"] == \"systemStats.ssCpuRawWait\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> derivative()\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"agent_host\", \"systemStats.ssCpuRawSystem\", \"systemStats.ssCpuRawUser\", \"systemStats.ssCpuRawWait\"])\r\n\r\njoin(\r\n    tables: { numCpus: numCpus, stats: stats },\r\n    on: [\"_time\", \"_start\", \"_stop\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    \"systemStats.ssCpuRawSystem\": r[\"systemStats.ssCpuRawSystem\"] / float(v: r[\"systemStats.ssCpuNumCpus\"]),\r\n    \"systemStats.ssCpuRawUser\": r[\"systemStats.ssCpuRawUser\"] / float(v: r[\"systemStats.ssCpuNumCpus\"]),\r\n    \"systemStats.ssCpuRawWait\": r[\"systemStats.ssCpuRawWait\"] / float(v: r[\"systemStats.ssCpuNumCpus\"]),\r\n  }))\r\n  |> drop(columns: [\"systemStats.ssCpuNumCpus\"])"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory.memTotalReal\" or r[\"_field\"] == \"memory.memAvailReal\" or r[\"_field\"] == \"memory.memBuffer\" or r[\"_field\"] == \"memory.memCached\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ \r\n      r with \r\n      _value: 100.0 - ((float(v: r[\"memory.memAvailReal\"]) + float(v: r[\"memory.memBuffer\"]) + float(v: r[\"memory.memCached\"])) / float(v: r[\"memory.memTotalReal\"]) * 100.0) \r\n  }))\r\n  |> group(columns: [\"source\", \"_field\", \"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Network Usage - Traffic Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHCOutOctets\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> group(columns: [\"ifName\",\"agent_host\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: ${interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"nonnegative derivative\")\r\n"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.network\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifHCInOctets\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> group(columns: [\"ifName\",\"agent_host\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: ${interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.disk\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskTemperature\")\r\n  |> map(fn: (r) => ({ \"_time\": r[\"_time\"], \"_field\": \"CPU\", \"_value\": r[\"_value\"] }))\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.disk\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"diskTemperature\")\r\n  |> map(fn: (r) => ({ \"_time\": r[\"_time\"], \"_field\": r[\"diskID\"], \"_value\": r[\"_value\"] }))\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.volume\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hrStorageUsed\" or r[\"_field\"] == \"hrStorageSize\")\r\n  |> filter(fn: (r) => r[\"hrStorageDescr\"] =~ /^\\/volume\\d+/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: (float(v: r.hrStorageUsed) / float(v: r.hrStorageSize) * 100.0) }))\r\n  |> aggregateWindow(every: ${interval}, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"hrStorageSize\", \"hrStorageUsed\"])\r\n  |> yield(name: \"last\")\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.storageIO\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIOReads\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.storageIO\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIOWrites\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.storageIO\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIONReadX\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.Synology.storageIO\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storageIONWrittenX\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${synologyhostname:regex}/)\r\n  |> derivative()\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  }
 ]
}